version: '3.8'

services:
  vectordb:
    image: ankane/pgvector:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-railway}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: ${PGDATA:-/var/lib/postgresql/data/pgdata}
    volumes:
      - pgdata2:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5

  rag_api:
    image: ghcr.io/danny-avila/librechat-rag-api-dev:latest
    environment:
      - DB_HOST=${RAILWAY_PRIVATE_DOMAIN}
      - DB_PORT=${DB_PORT:-5432}
      - POSTGRES_DB=${POSTGRES_DB:-railway}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - EMBEDDINGS_PROVIDER=${EMBEDDINGS_PROVIDER:-openai}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=${RAG_PORT:-8000}
      - DEBUG_RAG_API=${DEBUG_RAG_API:-true}
    ports:
      - "${RAG_PORT:-8000}:${RAG_PORT:-8000}"
    depends_on:
      vectordb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${RAG_PORT:-8000}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  pgdata2:
